apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      name: "plaintext"
      port: 9092
      targetPort: 9092
    - protocol: TCP
      name: "controller"
      port: 9093
      targetPort: 9093
  type: ClusterIP
