apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotor
  template:
    metadata:
      labels:
        app: rotor
    spec:
      containers:
        - name: rotor
          image: jitsucom/rotor:2.8.5
          tty: true
          resources:
            requests:
              cpu: "512m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: rotor-config
          livenessProbe:
            httpGet:
              path: /health
              port: 3401
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3401
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 15