services:
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081" # Menghubungkan port localhost ke container
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

      # Host MongoDB eksternal
      # Mongodb server tidak pada stack yang sama, tapi masih dalam lingkup docker container
      # Sehingga bisa pakai host.docker.internal saja
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: "host.docker.internal"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: myuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypswd123
    restart: unless-stopped
