apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: jitsucom/console:2.8.5
          tty: true
          envFrom:
            - configMapRef:
                name: console-config
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "syncctl"
