apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: kafka
          image: "bitnami/kafka:3.6.0"
          tty: true
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 9092
            - containerPort: 9093
