apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  ME_CONFIG_BASICAUTH_USERNAME: "admin"
  ME_CONFIG_BASICAUTH_PASSWORD: "admin123"
  ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  # Host MongoDB eksternal
  # Mongodb ada di luar kluster, tapi masih di dalam docker, sehingga tidak bisa pakai host.docker.internal
  # Harus pakai IP mesin
  ME_CONFIG_MONGODB_SERVER: "192.168.88.230"
  ME_CONFIG_MONGODB_PORT: "27017"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "myuser"
  ME_CONFIG_MONGODB_ADMINPASSWORD: "mypswd123"
