apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  type: NodePort
  ports:
    - port: 8081        # Port yang digunakan di Service
      targetPort: 8081  # Port di dalam container
      nodePort: 8081    # Port yang diekspos di host (harus berada dalam rentang 30000-32767 secara default)
  selector:
    app: mongo-express
