apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  ME_CONFIG_BASICAUTH_USERNAME: "admin"
  ME_CONFIG_BASICAUTH_PASSWORD: "admin123"
  ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  # Host MongoDB eksternal
  ME_CONFIG_MONGODB_SERVER: "host.docker.internal"
  ME_CONFIG_MONGODB_PORT: "27017"
  ME_CONFIG_MONGODB_ADMINUSERNAME: "default"
  ME_CONFIG_MONGODB_ADMINPASSWORD: "mypswd123"