apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
    spec:
      containers:
        - name: ingest
          image: jitsucom/ingest:2.8.5
          tty: true
          envFrom:
            - configMapRef:
                name: ingest-config
          resources:
            requests:
              cpu: "128m"
              memory: "64Mi"
            limits:
              cpu: "256m"
              memory: "128Mi"
          ports:
            - containerPort: 3049
          livenessProbe:
            httpGet:
              path: /health
              port: 3049
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3049
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 15