apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
data:
  ROTOR_URL: "http://rotor:3401"
  ROTOR_AUTH_KEY: "myBulkerTokenIs123"
  BULKER_URL: "http://bulker:3042"
  CONSOLE_RAW_AUTH_TOKENS: "myConsoleTokenIs123"
  BULKER_AUTH_KEY: "myBulkerTokenIs123"
  MIT_COMPLIANT: "false"
  DATABASE_URL: "postgresql://postgres:mypswd123@host.docker.internal:5432/postgres?schema=newjitsu"
  SEED_USER_EMAIL: "admin@jitsu.com"
  SEED_USER_PASSWORD: "admin123"
  ENABLE_CREDENTIALS_LOGIN: "true"
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  SYNCS_ENABLED: "true"
  SYNCCTL_URL: "http://syncctl:3043"
  SYNCCTL_AUTH_KEY: "mySyncctlTokenIs123"
  GOOGLE_SCHEDULER_KEY: ""
  # JITSU_INGEST_PUBLIC_URL: "http://localhost:8080"
  JITSU_INGEST_PUBLIC_URL: "http://localhost:30080"
  # JITSU_PUBLIC_URL: "http://localhost:3000"
  JITSU_PUBLIC_URL: "http://localhost:30000"
  # NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_URL: "http://localhost:30000"
  CLICKHOUSE_HOST: "host.docker.internal:8123"
  CLICKHOUSE_USERNAME: "default"
  CLICKHOUSE_PASSWORD: "mypswd123"
  CLICKHOUSE_DATABASE: "newjitsu_metrics"
  MONGODB_URL: "mongodb://default:mypswd123@host.docker.internal/jitsu"
  MONGODB_NETWORK_COMPRESSION: "none"
  FORCE_UPDATE_DB: "true"